name: im
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.6+16

environment:
  sdk: ^3.5.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  # https://github.com/jonataslaw/getx/blob/master/README.zh-cn.md
  # 通用框架：国际化、状态管理、路由管理、主题管理 https://pub.dev/packages/get
  get: ^4.6.6
  # get: ^5.0.0-release-candidate-4
  # Localization https://github.com/dart-lang/intl
  intl: ^0.19.0
  # https://pub.dev/packages/equatable
  equatable: ^2.0.5
  # https://pub.dev/packages/flutter_bloc
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  # https://pub.dev/packages/http
  http: ^1.1.0
  http_parser: ^4.0.2
  # https://pub.dev/packages/sp_util
  sp_util: ^2.0.3
  # 图片选择插件 https://pub.dev/packages/image_picker
  image_picker: ^1.0.4
  # 事件通知总线 https://pub.dev/packages/event_bus
  # event_bus: ^2.0.0
  # https://pub.dev/packages/device_info_plus
  # device_info_plus: ^11.2.0
  # 处理键盘事件 https://pub.dev/packages/keyboard_actions
  keyboard_actions: ^4.2.0
  # 打开用户协议等网页 https://pub.dev/packages/url_launcher
  url_launcher: ^6.2.1
  # https://pub.dev/packages/pull_to_refresh
  pull_to_refresh: ^2.0.0
  # loading对话框 https://pub.dev/packages/flutter_easyloading
  flutter_easyloading: ^3.0.5
  # 下拉刷新 https://pub.dev/packages/easy_refresh
  easy_refresh: ^3.4.0
  # https://pub.dev/packages/logging
  # logging: ^1.1.1
  # https://pub.dev/packages/convert
  convert: ^3.1.1
  # 权限管理：语音等
  # https://pub.dev/packages/permission_handler
  # permission_handler: ^10.2.0
  # 缓存图片
  # https://pub.dev/packages/cached_network_image
  cached_network_image: ^3.4.0
  # 初次打开app，引导屏
  # https://pub.dev/packages/introduction_screen
  introduction_screen: ^3.1.14
  # https://pub.dev/packages/flutter_markdown
  # flutter_markdown: ^0.6.15
  # 打印log https://pub.dev/packages/logger
  logger: ^2.4.0
  # alert弹窗
  # https://pub.dev/packages/rflutter_alert
  # rflutter_alert: ^2.0.7
  # 微信分享 https://pub.dev/packages/fluwx
  # fluwx: ^4.5.5
  # 显示html https://pub.dev/packages/flutter_widget_from_html
  flutter_widget_from_html: ^0.15.1
  # html 点击查看大图 https://pub.dev/packages/photo_view
  photo_view: ^0.15.0
  # 适配屏幕：https://pub.dev/packages/flutter_adaptive_scaffold
  flutter_adaptive_scaffold: ^0.3.1
  # 本地存储Bloc状态 persists and restores bloc and cubit states
  # https://pub.dev/packages/hydrated_bloc
  hydrated_bloc: ^9.1.5
  # 富文本展示题目解析：https://pub.dev/packages/styled_text
  # styled_text: ^8.1.0
  # 监听截屏事件：https://pub.dev/packages/screenshot_callback
  # screenshot_callback: ^3.0.1
  # 获取截屏图片存储路径：https://pub.dev/packages/flutter_screenshot_callback
  # flutter_screenshot_callback: ^0.0.9
  # 自定义segment：https://pub.dev/packages/custom_sliding_segmented_control
  custom_sliding_segmented_control: ^1.7.5
  # mqtt长连接 https://pub.dev/packages/mqtt_client
  mqtt_client: ^10.5.1
  # https://pub.dev/packages/sqflite
  sqflite: ^2.3.3+1
  # https://pub.dev/packages/path
  path: ^1.9.0
  # https://pub.dev/packages/event_bus
  event_bus: ^2.0.0
  # https://pub.dev/packages/typed_data
  typed_data: ^1.3.2
  # 会话记录左滑 https://pub.dev/packages/left_scroll_actions
  left_scroll_actions: ^2.2.0
  # https://pub.dev/packages/wechat_assets_picker
  wechat_assets_picker: ^9.2.0
  # https://pub.dev/packages/wechat_camera_picker
  wechat_camera_picker: ^4.3.6
  # https://pub.dev/packages/extended_image
  extended_image: ^9.0.7
  # 获取应用版本信息 https://pub.dev/packages/package_info_plus
  package_info_plus: '>=5.0.0 <9.0.0'
  # https://pub.dev/packages/provider
  provider: ^6.0.2
  # H5-webchat https://pub.dev/packages/webview_flutter
  webview_flutter: ^4.8.0
  # https://pub.dev/packages/webview_flutter_android
  webview_flutter_android: ^3.16.6
  # https://pub.dev/packages/webview_flutter_wkwebview
  webview_flutter_wkwebview: ^3.14.0
  # toast https://pub.dev/packages/fluttertoast
  fluttertoast: ^8.2.8
  # 扫码
  # https://pub.dev/packages/mobile_scanner
  # https://github.com/juliansteenbakker/mobile_scanner
  # https://github.com/pengjinning/flutter_plugin_qrcode
  # mobile_scanner: ^6.0.2
  # https://pub.dev/packages/flutter_scankit/install
  # https://github.com/arcticfox1919/flutter-scankit
  # 不支持模拟器
  # flutter_scankit: ^2.0.4
  # 收到消息震动 https://pub.dev/packages/flutter_vibrate
  # flutter_vibrate: ^1.3.0
  # 播放视频 https://pub.dev/packages/video_player
  video_player: ^2.9.1
  # 视频thumbnail https://pub.dev/packages/video_thumbnail
  # video_thumbnail: ^0.5.3
  # 长按桌面图标-自定义快捷方式 https://pub.dev/packages/quick_actions
  quick_actions: ^1.0.7
  # 系统自带分享，分享聊天内容到微信等App https://pub.dev/packages/share_plus
  share_plus: ^10.0.0
  # 接收其他应用分享的文件 https://pub.dev/packages/share_handler
  share_handler: ^0.0.21
  # 录音，发语音消息 https://pub.dev/packages/audio_session
  audio_session: ^0.1.21
  # 录音，发语音消息 https://pub.dev/packages/flutter_sound
  flutter_sound: ^9.15.61
  # 录音，发语音消息 https://pub.dev/packages/path_provider
  # 为hydrated_bloc提供路径服务
  path_provider: ^2.1.4
  # 录音，发语音消息 https://pub.dev/packages/permission_handler
  permission_handler: ^11.3.1
  # 消息推送 https://pub.dev/packages/push
  push: ^2.3.0
  # https://pub.dev/packages/flutter_local_notifications
  flutter_local_notifications: ^18.0.1
  # 网络连接状态 https://pub.dev/packages/connectivity_plus
  connectivity_plus: ^6.0.5
  # 录音
  flutter_plugin_record_plus:
    path: import/flutter_plugin_record_plus
  # flutter_plugin_record:
  #   git:
  #    url: https://gitee.com/270580156/flutter_plugin_record.git
  # 汉字转拼音 https://pub.dev/packages/lpinyin
  lpinyin:
    git:
      # url: https://github.com/pengjinning/lpinyin
      url: https://gitee.com/270580156/lpinyin.git
  # 通讯录、城市选择列表 https://pub.dev/packages/azlistview
  # 源库不更新，所以直接使用源码集成
  azlistview:
    git:
      # url: https://github.com/pengjinning/azlistview
      url: https://gitee.com/270580156/azlistview.git
  # https://pub.dev/packages/qr_flutter
  # qr_flutter: ^4.1.0 # 报错
  qr_flutter:
    git:
      # url: https://github.com/pengjinning/qr.flutter
      url: https://gitee.com/270580156/qr.flutter.git
  # TODO:语音转文本、文本转语音
  # 微语flutter sdk
  # bytedesk_flutter:
  #   path: ../bytedesk-sdk-private/bytedesk_flutter
  # 客服SDK
  bytedesk_kefu:
    path: ../../packages/bytedesk_kefu
  # 推送SDK
  bytedesk_push:
    path: ../../packages/bytedesk_push
  # 通用SDK
  bytedesk_common:
    path: ../../packages/bytedesk_common
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  # 开屏splash
  # 添加完配置后，要执行：dart run flutter_native_splash:create --path=./flutter_native_splash.yaml
  # https://pub.dev/packages/flutter_native_splash
  flutter_native_splash: ^2.4.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/
    - assets/images/chat/
    - assets/images/common/
    - assets/images/login/
    - assets/images/feedback/
    - assets/images/contact/
    - assets/json/
    - assets/onboard/
    - assets/audio/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

#
fluwx:
  app_id: wx18794ee1079489ce
  # only debug in debug mode
  debug_logging: true
  android:
  #    interrupt_wx_request: true # default is true
  #    flutter_activity: MainActivity #Default to launch app's launcher
  ios:
    universal_link: https://app.weiyuai.cn/
    scene_delegate: false #default false
  # payment is enabled by default
  no_pay: true
